#!/bin/tcsh
#
#-------------------------------------------
#  Uninstall PUPS/P3 and support components
#  $1 logfile
#
#  (C) M.A. O'Neill. Tumbling Dice 2000-2024
#-------------------------------------------

pushd pupscore.src		>& /dev/null
./unistall_puopsP3.csh $1
pops				>& /dev/null

exit 0
