.TH ADDRESS 1 "8th February 2009" "PUPSP3 build tools" "PUPSP3 3build tools"

.SH NAME
ADDRESS \- get addressing (pointer) size in byes 
.br

.SH SYNOPSIS
.B address 
.I string 
>& <log file>
.br

.SH DESCRIPTION
.I address(1)
get the the pointer size for the current architecture in bytes and prints the
result to
.I standard output.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
