.TH DOWNCASE 1 "8th February 2009" "PUPSP3 build tools" "PUPSP3 build tools"

.SH NAME
DOWNCASE \- convert argument string to lower case 
.br

.SH SYNOPSIS
.B downcase 
.I string 
[2> <log file>]
.br

.SH DESCRIPTION
.I downcase(1)
converts argument
.I string
to lower case and then prints the result to
.I standard output.
.br

.SH EXIT STATUS

255: error
.br
1:
.B -usage
or
.B -help
.br
0: no error
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
