.TH ISHEX 1 "22 February 2005" "PUPSP3 build tools" "PUPSP3 build tools"

.SH NAME
ISHEX \- test to see if string is a hexadecimal number 
.br

.SH SYNOPSIS
.B ishex 
.I string 
>& <log file>
.br

.SH DESCRIPTION
.I ishex(1)
tests to see if its argument string is a hexadecimal number. If it is,
it prints the string
.B TRUE
and the corresponding decimal value to
.I standard output.
If not, the string
.B FALSE
is printed to
.I standard output 
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
