.TH ISINT 1 "8th February 2009" "PUPSP3 build tools" "PUPSP3 build tools"

.SH NAME
ISINT \- test to see if string is a integer number 
.br

.SH SYNOPSIS
.B isint 
.I string 
[2> <log file>]
.br

.SH DESCRIPTION
.I isint(1)
tests to see if its argument string is an ineteger number. If it is,
it prints the string
.B TRUE
and the corresponding decimal value to
.I standard output.
If not, the string
.B FALSE
is printed to
.I standard output 
.br

.SH EXIT STATUS

255: error
.br
1:
.B -usage
or
.B -help
.br
0: no error
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
