.TH MANC 1 "11th January 2008" "PUPSP3 Scripts" "PUPSP3 Scripts"

.SH NAME
MANC \- generate man page from C/C++ source using c2man application. 
.br

.SH SYNOPSIS
.B manc 
.I C/C++ source file name
.I man page name 
[2> <log file>]
.br

.SH DESCRIPTION
.I manc(1)
generates
.B man
pages for
.B PUPSP3/P3
source files using the
.I c2man(1)
application
.br

.SH OPTIONS

None.
.br

.SH EXIT STATUS

255: error
.br
1:
.B -usage
or
.B -help
.br
0: no error
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br

.SH SEE ALSO
c2man(1)

