.TH MKFILE 1 "30th December 2002" "PUPSP3 build tools" "PUPSP3 build tools"

.SH NAME
MKTTY \- PUPS file creation utility.
.br

.SH SYNOPSIS
.B mkfile [-help | -usage] | <name> <(octal> permisions>
[2> <log file>]
.br

.SH DESCRIPTION
.I mkfile(1)
is a utility which permits the user to create arbitrary files and
to assign arbitrary permissions to the file which are created. This
utility is mainly used by scripts (such as the
.I pups(7)
creation and installation scripts
.I build_pups_services(1)
and
.I install_pups_services(3)
.br
Optionally the user can set file permissions (in octal). Default
permissions are 0600 (-rw-------).
.br


.SH OPTIONS
.B -help | -usage
prints out usage string. The application then exists (with return
code 1).
.br

.SH EXIT STATUS

255: error
.br
1:
.B -usage
or
.B -help
.br
0: no error
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br

.SH SEE ALSO
pups(7), install_pups_services(1), build_pups_services(1)
.br
