.TH P3L2MAN 1 "11 January 2008" "PUPSP3 Scripts" "PUPSP3 Scripts"

.SH NAME
P3L2MAN \- generate man page stubs for all current PUPSP3 library functions. 
.br

.SH SYNOPSIS
.B P3L2MAN 
.I man page directory 
>& <log file>
.br

.SH DESCRIPTION
.I P3L2MAN(1)
uses
.I c2man(1)
to generate man page stubs for all P3 library functions. These man page stubs are written to
.I man page directory
which defaults to
.B c2man
in the current directory.
.br


.SH OPTIONS

None.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br

.SH SEE ALSO
c2man(1)
