.TH PSRPTOOL 1 "16th April 2015" "PUPSP3 Scripts" "PUPSP3 Scripts"

.SH NAME
PSRPTOOL \- wrapper for psrptool application 
.br

.SH SYNOPSIS
.B PSRPTOOL 
>& <log file>
.br

.SH DESCRIPTION
.I PSRPTOOL(1)
is simply a wrapper for the
.I psrptool(1)
application which starts an instance of
.I psrp(1)
in its own
.I xterm(1)
window.
.br


.SH OPTIONS

None.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br

.SH SEE ALSO
psrp(1), xterm(1)

