.TH PUPSUNAME 1 "26 April 2002" "PUPSP3 Scripts" "PUPSP3 Scripts"

.SH NAME
PUPSUNAME \- display CPU and operating system architectures string.

.br

.SH SYNOPSIS
.B pups_uname 
.I [usage | --usage] 
.I !object file name!
>& <log file>
.br

.SH DESCRIPTION
.I pups_uname(1)
is a
.I csh(1)
shellscript which prints the  CPU and operating system architectures string on standard output.
It is used by many of the automated scripts which build and maintain the PUPSP3 environment.
.br


.SH OPTIONS

.B -usage
.B --usage 
prints out help information about
.I pups_uname(1)
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br

.SH SEE ALSO
csh(1)
.br
