.TH STRIPLC 1 "15th November 2003" "PUPSP3 build tools" "PUPSP3 build tools"

.SH NAME
STRIPLC \- strip last character in argument string 
.br

.SH SYNOPSIS
.B striplc 
.B [-usage | -help]
< <stdin>
[2> <log file>]
.br

.SH DESCRIPTION
.I striplc(1)
strips the last character in the character string read from
.I standard input.
This utility is used by
.I pups(3)
build scripts.
.br

.SH OPTIONS

.B -usage | -help
display help and copyright information for the
.I tas(1)
filter.
.br

.SH EXIT STATUS

255: error
.br
1:
.B -usage
or
.B -help
.br
0: no error
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
