.TH TMPWIPE 1 "11 January 2008" "PUPSP3 Scripts" "PUPSP3 Scripts"

.SH NAME
TMPWIPE \- remove stale PSRP resources from /tmp directory. 
.br

.SH SYNOPSIS
.B TMPWIPE 
>& <log file>
.br

.SH DESCRIPTION
.I TMPWIPE(1)
removes stale resources (PSRP lockpost files, PSRP channels and defunct locks) from
.I /tmp.
.br


.SH OPTIONS

None.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
