.TH UPCASE 1 "8th February 2009" "PUPSP3 build tools" "PUPSP3 build tools"

.SH NAME
UPCASE \- convert argument string to upper case 
.br

.SH SYNOPSIS
.B upcase 
.I string 
>& <log file>
.br

.SH DESCRIPTION
.I upcase(1)
converts argument
.I string
to upper case and then prints the result to
.I standard output.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
