.TH WIPE 1 "11 January 2008" "PUPSP3 Scripts" "PUPSP3 Scripts"

.SH NAME
WIPE \- remove stale PSRP resources from a PSRP channel directory. 
.br

.SH SYNOPSIS
.B WIPE 
.I PSRP channel directory name 
>& <log file>
.br

.SH DESCRIPTION
.I WIPE(1)
removes stale resources (PSRP lockpost files, PSRP channels and defunct locks) from the specified
PSRP channel directory.
.br


.SH OPTIONS
.B PSRP channel directory name
directory to be scanned for stale resources.
.br

.SH ENVIRONMENT VARIABLES
None.
.br

.SH COPYRIGHT
(C) Tumbling Dice Ltd.
.br

.SH PROGRAMMER
M.A. O'Neill.
.br
